### ISSUE TITLE
KNN imputation not working for 48 GEO datasets

### ISSUE THREAD

**Issue by IsmailM** [GeoDiver/R-Core#110]
the `impute.knn` function fails for 48 GEO datasets.

The `tryCatch` loop catches this error and produces the following errors:

```
ERROR: Bad dataset: Unable to run KNN imputation on the dataset.
```

[Knnimputation.txt](https://github.com/SBCS-Bioinformatics/R-Core/files/204956/Knnimputation.txt)

**Comment by IsmailM** [comment]
What's the update on this?

**Comment by sureshhewabi** [comment]
need to fix #112 first to continue working on this. Most probably this issue(#110) is very old and I hope it is does not exist now.

**Comment by IsmailM** [comment]
I've fixed #112 - This still exists unfortunately...

I remember that we used to simply remove rows with missing data - so why not simply remove the entire row if the KNN imputation fails (i.e. in the `tryCatch` block) - it's better than failing the whole analysis.

What do you think?

**Comment by sureshhewabi** [comment]
I think it fails because there are some genes that contain 0.0000 for all the samples

<img width="668" alt="image" src="https://cloud.githubusercontent.com/assets/5387193/20857056/fcf62496-b946-11e6-9987-f38dc8ef0e09.png">

Therefore, I think we can remove entire row I guess.

**Comment by sureshhewabi** [comment]
Adding code in bold will fix the issue:

```
if (ncol(X) == 2){
  X <- X[complete.cases(X), ] # KNN does not work when there are only 2 samples
} else {
  X <- X[rowSums(is.na(X)) != ncol(X), ] # remove rows with missing data
}

**# remove all zeros
X <- X[rowSums(X != 0) != 0,]**
```

I tested few of the datasets failed earlier, and now with this fix, there are working
